name: better_drop_down
description: A customizable Flutter dropdown widget with enhanced UI, hover effects, and Material Design styling.
version: 1.0.3
homepage: https://github.com/chhamed/better_drop_down
repository: https://github.com/chhamed/better_drop_down
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1